[workspace]
members = ["library/nh3-core","nh3"]
resolver = "3"

[workspace.dependencies]
nh3-core = { path = "library/nh3-core" }

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
unwrap_used = "deny"
