[workspace]
resolver = "3"
members = ["library/nh3-parser", "library/nh3-lexer"]

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
unwrap_used = "deny"

[workspace.dependencies]
nh3-lexer = { path = "library/nh3-lexer" }
